### ISSUE TITLE
Tagging the most recent commit

### ISSUE THREAD

**Issue by TheCynosure** [RobotLocomotion/models#15]
Hello I would like to use some of your models that are used inside the Drake project. The Drake project uses your newest commit, could you possibly tag that commit? I am unable to use un-tagged code.
Thanks,
Jack

**Comment by jwnimmer-tri** [comment]
I discussed within the team, and we'd propose tagging this repository at the latest commit (745547fbec8ec8cb10be6ef23f7f0cd5ba49d321) using tag name `0.0.20200827` to match the date of that commit.

For any future Drake releases that refer to a newer commit, we'd also tag those newer commits using the same pattern (the date of the commit).

Does that work for you, @TheCynosure?

**Comment by TheCynosure** [comment]
That's perfect!

**Comment by jwnimmer-tri** [comment]
Process docs => https://github.com/RobotLocomotion/drake/pull/15770.

Once those are signed off, we'll add the tag here.

**Comment by jwnimmer-tri** [comment]
Done

https://github.com/RobotLocomotion/models/releases/tag/v0.0.20200827
